version: '3.8'

services:
  backend:
    build:
      context: ./Backend/main_frame_project
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./Backend/main_frame_project:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "./manage.py", "runserver", "0.0.0.0:8000"]

  frontend:
    build:
      context: ./Frontend/portfolioResume
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./Frontend/portfolioResume:/app
    stdin_open: true
    tty: true