name: Run Angular Unit Tests with Jasmine and Karma

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install project dependencies
        run: npm ci

      - name: Run Angular unit tests with Karma
        run: ng test --watch=false --browsers=ChromeHeadless
