name: Test Docker Compose

on: [push]

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.9
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run docker-compose up
        run: |
          docker compose up -d
          sleep 30
          
      - name: Test Node.js service with curl
        run: |
            SERVICE_URL="http://localhost:8000"
            EXPECTED_RESPONSE="Hello, World!"
            RESPONSE=$(curl -sSf $SERVICE_URL)
            if [ "$RESPONSE" == "$EXPECTED_RESPONSE" ]; then
                echo "Test Passed: Service returned expected response."
                echo "Expected: $EXPECTED_RESPONSE"
                echo "Actual: $RESPONSE"
                exit 0
            else
                echo "Test Failed: Service response did not match expected response."
                echo "Expected: $EXPECTED_RESPONSE"
                echo "Actual: $RESPONSE"
                exit 1
            fi

      - name: Clean up
        run: docker compose down
