name: Test Docker Compose



on:

  [push]

jobs:

  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3



      - name: Run docker-compose up

        run: docker compose up -d



    #   - name: Check service logs

    #     run: docker logs webserver



    #   - name: Perform API test

    #     run: curl -X GET http://localhost:8080/health | grep 'OK'



      - name: Clean up

        run: docker compose down
