name: Docker Compose

on: 
  workflow_call: # Allows this workflow to be reused
    inputs:
      compose-file:
        description: 'Compose file path'
        default: 'docker-compose.yml'
        type: string

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.9
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run docker-compose up
        run: |
          docker compose -f ${{ inputs.compose-file }} up -d
          sleep 30

      - name: Run docker-compose down
        if: always() # Ensure cleanup happens even if previous steps fail
        run: docker compose -f ${{ inputs.compose-file }} down
