name: Python Unit Tests
on:
  [push]
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
   
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Backend/controller/requirements.txt
  
    - name: Run your tests
      run: Backend/controller/test/test_runner.py

  