name: Reusable Workflow User

on: [push]

jobs:
  call-workflow-in-local-repo:
    uses: ./.github/workflows/dockerCompose.yml

  call-workflow-in-local-repo-2:
    uses: ./.github/workflows/automationTestingWithPlaywright.yml
