name: Reusable Workflow User

on: [push]

jobs:
  call-workflow-in-local-repo:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Call workflow in local repo
        uses: ./.github/workflows/dockerCompose.yml
      - name: Call workflow in local repo 2
        uses: ./.github/workflows/automationTestingWithPlaywright.yml


