name: reusable worflow user

on: [push]

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Launching docker compose
        uses: ./.github/workflows/dockerCompose.yml

      - name: Conducting Playwright python automation test
        uses: ./.github/workflows/automationTestingWithPlaywright.yml

      - name: Clean up
        run: docker compose down
