name: reusable worflow user

on: [push]

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:

        - uses: actions/checkout@v2
        - name: Launching Docker Compose
          uses: ./.github/workflows/dockerCompose.yml@main
  
        - name: Conducting Playwright Python Automation Test
          uses: ./.github/workflows/automationTestingWithPlaywright.yml@main
