name: Reusable Workflow User

on: [push]

jobs:
  call-workflow-in-local-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Sets up docker
        uses: ./.github/workflows/dockerCompose.yml
      - name: runs playwright automation test with python
        uses: ./.github/workflows/automationTestingWithPlaywright.yml
      - name: cleans up the docker containers
        run: docker compose down
